apiVersion: v1
kind: Namespace
metadata:
  name: go-http-server
  labels:
    app.kubernetes.io/name: go-http-server
    app.kubernetes.io/component: api-server
    app.kubernetes.io/part-of: application
