apiVersion: v1
kind: Secret
metadata:
  name: go-http-server-secrets
  namespace: go-http-server
  labels:
    app.kubernetes.io/name: go-http-server
    app.kubernetes.io/component: api-server
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_IN_PRODUCTION"