name: CI

on:
  push:
    branches: [ "master", "main" ]
    paths-ignore:
      - '**.md'
      - 'deployments/**'
      - '.gitignore'
      - 'Makefile'
  pull_request:
    branches: [ "master", "main" ]
    paths-ignore:
      - '**.md'
      - 'deployments/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}

permissions:
  contents: write

jobs:
  build-and-push:
    uses: davidsugianto/shared-workflows/.github/workflows/go-docker-ci.yaml@master
    with:
      go-version: "1.25"
      image-name: "docker.io/idiots718/go-http-server"
      run-tests: false
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  update-image-tag-staging:
    needs: build-and-push
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main'
    uses: davidsugianto/shared-workflows/.github/workflows/kustomize-image-tag.yaml@master
    with:
      image: "docker.io/idiots718/go-http-server"
      tag: ${{ needs.build-and-push.outputs.image-tag }}
      kustomize-path: "go-http-server/deployments/kubernetes/overlays/staging"
    secrets:
      GIT_TOKEN: ${{ secrets.PAT_TOKEN }}

  update-image-tag-production:
    needs: build-and-push
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    uses: davidsugianto/shared-workflows/.github/workflows/kustomize-image-tag.yaml@master
    with:
      image: "docker.io/idiots718/go-http-server"
      tag: ${{ needs.build-and-push.outputs.image-tag }}
      kustomize-path: "go-http-server/deployments/kubernetes/overlays/production"
    secrets:
      GIT_TOKEN: ${{ secrets.PAT_TOKEN }}